name: Run Jupyter Notebook

on:
  schedule:
    # Runs at the top of every hour
    - cron:  '30'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install notebook nbconvert ipykernel
        # Install any other dependencies
        pip install numpy pandas matplotlib # Example libraries

    - name: Execute Jupyter notebook
      run: |
        jupyter nbconvert --to notebook --execute scraping.ipynb --output scraping.ipynb

    - name: Commit and push if there were changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update Notebook" || echo "No changes to commit"
        git push
